# Generated by Django 3.1.5 on 2021-05-22 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('param', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='empresa_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='param.empresa'),
        ),
    ]
