# Generated by Django 3.1.5 on 2021-05-22 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('param', '0003_auto_20210522_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='empresa_id',
            new_name='company',
        ),
    ]
