# Generated by Django 3.1.5 on 2021-06-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('param', '0005_auto_20210602_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(null=True, upload_to='img/empresa/'),
        ),
    ]
