# Generated by Django 3.1.5 on 2021-08-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('param', '0008_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='plataforma',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Carousel', 'Carousel'), ('YouTube', 'YouTube'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn')], default='Facebook', max_length=20),
        ),
    ]
