# Generated by Django 3.1.5 on 2021-08-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('param', '0010_auto_20210813_0053'),
        ('param', '0009_empresa_tributa'),
    ]

    operations = [
    ]
