# Generated by Django 3.1.5 on 2021-10-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('param', '0012_auto_20210828_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.CharField(choices=[('Colombia', 'Colombia'), ('Ecuador', 'Ecuador')], default='Colombia', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='¿Staff?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Username'),
        ),
    ]
