# Generated by Django 3.1.5 on 2021-05-28 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('param', '0004_auto_20210522_1435'),
        ('cmp', '0002_comprasdet_comprasenc'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasdet',
            name='empresa',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='param.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comprasenc',
            name='empresa',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='param.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='empresa',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='param.empresa'),
            preserve_default=False,
        ),
    ]
