# Generated by Django 3.1.5 on 2021-10-06 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('param', '0013_auto_20211006_1027'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('rol', models.CharField(help_text='Rol', max_length=100)),
                ('salario', models.FloatField(default=0)),
                ('dias_laborales', models.IntegerField(default=30)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('identificacion', models.CharField(help_text='Identificación', max_length=20, unique=True)),
                ('nombres', models.CharField(help_text='Nombres', max_length=100)),
                ('apellidos', models.CharField(help_text='Apellidos', max_length=100)),
                ('direccion', models.CharField(help_text='Dirección', max_length=300)),
                ('celular', models.CharField(blank=True, help_text='celular', max_length=20, null=True)),
                ('correo', models.CharField(help_text='Correo', max_length=60)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='param.empresa')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta.rol')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
