# Generated by Django 3.1.5 on 2021-10-08 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('param', '0013_auto_20211006_1027'),
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='empresa',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='param.empresa'),
            preserve_default=False,
        ),
    ]
