# Generated by Django 3.1.5 on 2021-10-27 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conta', '0002_rol_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='correo',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='identificacion',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombres',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('siglas', models.CharField(blank=True, max_length=10, null=True)),
                ('recargo', models.FloatField(default=0)),
                ('factor', models.FloatField()),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'HorasExtras',
            },
        ),
        migrations.CreateModel(
            name='EmpleadoHorasExtras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('horas', models.FloatField(default=8, null=True)),
                ('valor_hora', models.FloatField()),
                ('total', models.FloatField()),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateTimeField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta.empleado')),
                ('hora_extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta.horaextra')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
