# Generated by Django 3.1.5 on 2021-10-27 06:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conta', '0003_auto_20211027_0108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmpleadoHorasExtras',
            new_name='EmpleadoHoraExtra',
        ),
    ]
