# Generated by Django 3.1.5 on 2021-07-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vnt', '0003_productoscotizacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hola',
        ),
    ]
