# Generated by Django 3.1.5 on 2021-01-25 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_producto_subcategoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='unidadmedida',
            new_name='unidad_medida',
        ),
    ]
