# Generated by Django 3.1.5 on 2021-01-25 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0008_auto_20210125_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inv.unidadmedida'),
        ),
    ]
