# Generated by Django 3.1.5 on 2021-01-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0009_auto_20210125_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tiene_iva',
            field=models.BooleanField(default=False),
        ),
    ]
