# Generated by Django 3.1.5 on 2021-06-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0013_auto_20210527_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.FileField(null=True, upload_to='img/productos'),
        ),
    ]
