# Generated by Django 3.1.5 on 2021-02-03 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0002_comprasdet_comprasenc'),
        ('fac', '0004_auto_20210126_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaenc',
            name='proveedor',
            field=models.ForeignKey(default=None,on_delete=django.db.models.deletion.CASCADE, to='cmp.proveedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(max_length=13),
        ),
    ]
