# Generated by Django 3.1.5 on 2021-02-04 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0005_auto_20210202_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaenc',
            name='fecha_compra',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='fecha_factura',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='no_factura',
            field=models.CharField(blank=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
