# Generated by Django 3.1.5 on 2021-02-04 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0007_auto_20210203_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaenc',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fac.cliente'),
        ),
    ]
