# Generated by Django 3.1.5 on 2021-02-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0008_auto_20210204_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturadet',
            name='precio_prv',
            field=models.FloatField(default=0),
        ),
    ]
