# Generated by Django 3.1.5 on 2021-02-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0009_facturadet_precio_prv'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturadet',
            name='costo',
            field=models.FloatField(default=0),
        ),
    ]
