# Generated by Django 3.1.5 on 2021-06-05 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0003_auto_20210528_0239'),
        ('fac', '0011_auto_20210528_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaenc',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmp.proveedor'),
        ),
    ]
