# Generated by Django 3.1.5 on 2021-07-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0014_auto_20210703_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaenc',
            name='no_factura',
            field=models.IntegerField(auto_created=True, null=True),
        ),
    ]
