# Generated by Django 3.1.5 on 2021-07-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0015_auto_20210703_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaenc',
            name='no_factura',
            field=models.IntegerField(null=True),
        ),
    ]
